# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: beda5c08084df666dfb48c06b42ec0ff9630c7f011c0148c00eced4564d68846fdadbab70b5b5404d09e99ed8274b447874bcd68239cbad4d2d0612681fdee64

test:
  secret_key_base: 7f24fcd08607d4d2fcf21fd13759a1e37ed059e0b66d2d7f6c97441fc9afd3b7881d8fada6155f37a1fca2f1321bfc4c288e1463e582e0647136f79db3f5d9c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
